M48
; DRILL file {KiCad (6.0.1)} date Sat Apr  2 11:09:13 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-04-02T11:09:13-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X92.5Y-92.25
X92.533Y-68.175
X115.783Y-68.2
X115.783Y-92.25
X147.525Y-96.9
X167.725Y-78.85
X170.4Y-96.925
T0
M30
